
const data = [
  {
    id: 6,
    genus: "Genus: Malus",
    name: "Apple",
    family: "Family: Rosaceae",
    description:"Nutricions: carbohydrates: 11.4, protein: 0.3, fat: 0.4, calories: 52, sugar: 10.3",
    order: "Order: Rosales",
    image: "https://i1.wp.com/www.felizmelhoridade.com.br/wp-content/uploads/2018/04/Ma%C3%A7%C3%A3-%E2%80%93-Formas-de-comer-e-indica%C3%A7%C3%B5es.jpg?fit=1024%2C978&ssl=1",
    price: 2100,
  },
  {
    id: 35,
    genus: "Genus: Prunus",
    name: "Apricot",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"Nutricions: carbohydrates: 3.9, protein: 0.5, fat: 0.1, calories: 15, sugar: 3.2",
    image:"https://www.thespruceeats.com/thmb/EO4u2-KE35g-b5pt9A4vrn5FhEA=/2121x1414/filters:no_upscale():max_bytes(150000):strip_icc()/apricotKaanates-acc45833288a48b68dced11e62f3b555.jpg",
  },
  {
    id: 1,
    genus: "Genus: Musa",
    name: "Banana",
    family: "Family: Musaceae",
    order:"Order: Zingiberales",
    description:"Nutricions: carbohydrates: 22, protein: 1, fat: 0.2, calories: 96, sugar: 17.2 ",
    image:"https://img.freepik.com/fotos-premium/bando-de-banana-isolado_88281-1027.jpg?w=2000",
  },
  {
    id: 64,
    genus: "Genus: Rubus",
    name: "Blackberry",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"Nutricions: carbohydrates: 9, protein: 1.3, fat: 0.4, calories: 40, sugar: 4.5",
    image:"https://st.depositphotos.com/1000141/1662/i/450/depositphotos_16621795-stock-photo-blackberry-with-leaves.jpg",
  },
  {
    id: 33,
    genus: "Genus: Fragaria",
    name: "Blueberry",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"Nutricions: carbohydrates: 5.5, protein: 0, fat: 0.4, calories: 29, sugar: 5.4",
    image:"http://d3ugyf2ht6aenh.cloudfront.net/stores/001/194/977/products/mirtilo1-763767cf8dc5b6ca9c15899111001816-640-0.jpg",
  },
  {
    id: 9,
    genus: "Genus: Prunus",
    name: "Cherry",
    family: "Family: Rosaceae",
    order:"Order: None",
    description:"Nutricions: carbohydrates: 12, protein: 1, fat: 0.3, calories: 50, sugar: 8",
    image:"https://5285.cdn.simplo7.net/static/5285/sku/e-liquids-Eliquid-cereja-1520862600532.jpg",
  },
  {
    id: 60,
    genus: "Genus: Durio",
    name: "Durian",
    family: "Family: Malvaceae",
    order:"Order: Malvales",
    description:"Nutricions: carbohydrates: 27.1, protein: 1.5, fat: 5.3, calories: 147, sugar: 6.75",
    image:"https://f.i.uol.com.br/fotografia/2019/05/13/15577559415cd97825ee75d_1557755941_3x2_rt.jpg",
  },
  {
    id: 68,
    genus: "Genus: Ficus",
    name: "Fig",
    family: "Family: Moraceae",
    order:"Order: Malvales",
    description:"Nutricions: carbohydrates: 19, protein: 0.8, fat: 0.3, calories: 74, sugar: 16",
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROicj8REfIl8oDr2hQSpTJLYBdDT24R7ghPQ&usqp=CAU",
  },
  {
    id: 69,
    genus: "Genus: Ribes",
    name: "Gooseberry",
    family: "Family: Grossulariaceae",
    order:"Order: Saxifragales",
    description:"Nutricions:  carbohydrates: 10, protein: 0.9, fat: 0.6, calories: 44, sugar: 0",
    image:"https://thumbs.dreamstime.com/b/inteiro-e-sec%C3%A7%C3%A3o-transversal-da-fruta-do-gooseberry-20607956.jpg",
  },
  {
    id: 47,
    genus: "Genus: Vitis",
    name: "Grapes",
    family: "Family: Vitaceae",
    order:"Order: Vitales",
    description:"Nutricions:  carbohydrates: 18.1, protein: 0.72, fat: 0.16, calories: 69, sugar: 15.48",
    image:"https://st3.depositphotos.com/5393888/34713/i/450/depositphotos_347133648-stock-photo-fresh-pink-red-grape-isolated.jpg",
  },
  {
    id: 72,
    genus: "Genus: Malus",
    name: "GreenApple",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"Nutricions:  carbohydrates: 3.1, protein: 0.4, fat: 0.1, calories: 21, sugar: 6.4",
    image:"https://st3.depositphotos.com/1024764/37260/i/450/depositphotos_372609104-stock-photo-single-ripe-green-apple-fruit.jpg",
  },
  {
    id: 37,
    genus: "Genus: Psidium",
    name: "Guava",
    family: "Family: Myrtaceae",
    order:"Order: Myrtales",
    description:"Nutricions: carbohydrates: 14, protein: 2.6, fat: 1, calories: 68, sugar: 9",
    image:"https://thumbs.dreamstime.com/b/guava-isolada-um-fruto-de-goiaba-verde-inteiro-e-meio-com-polpa-rosa-num-galho-folhas-isoladas-em-fundo-branco-uma-inteira-meia-224856647.jpg",
  },
  {
    id: 66,
    genus: "Genus: Apteryx",
    name: "Kiwi",
    family: "Family: Actinidiaceae",
    order:"Order: Struthioniformes",
    description:"Nutricions: carbohydrates: 15, protein: 1.1, fat: 0.5, calories: 61, sugar: 9",
    image:"https://img.freepik.com/fotos-premium/kiwi-verde-fresco-isolado-em-um-fundo-branco-frutas-tropicais-close-up_186456-3182.jpg",
  },
  {
    id: 26,
    genus: "Genus: Citrus",
    name: "Lemon",
    family: "Family: Rutaceae",
    order:"Order: Sapindales",
    description:"Nutricions: carbohydrates: 9, protein: 1.1, fat: 0.3, calories: 29, sugar: 2.5",
    image:"https://img.freepik.com/fotos-gratis/frutas-de-limao-no-fundo-branco_181303-4999.jpg",
  },
  {
    id: 44,
    genus: "Genus: Citrus",
    name: "Lime",
    family: "Family: Rutaceae",
    order:"Order: Sapindales",
    description:"Nutricions:carbohydrates: 8.4, protein: 0.3, fat: 0.1, calories: 25, sugar: 1.7",
    image:"https://img.myloview.com.br/posters/limes-fruta-e-uma-fatia-fresca-no-fundo-branco-700-56564501.jpg",
  },
  {
    id: 65,
    genus: "Genus: Vaccinium",
    name: "Lingonberry",
    family: "Family: Ericaceae",
    order:"Order: Ericales",
    description:"carbohydrates: 11.3, protein: 0.75, fat: 0.34, calories: 50, sugar: 5.74",
    image:"https://media.istockphoto.com/photos/lingonberry-jam-and-lingonberries-in-glass-bowls-over-white-picture-id611335078",
  },
  {
    id: 67,
    genus: "Genus: Litchi",
    name: "Lychee",
    family: "Family: Sapindaceae",
    order:"Order: Sapindales",
    description:"carbohydrates: 17, protein: 0.8, fat: 0.44, calories: 66, sugar: 15",
    image:"https://thumbs.dreamstime.com/b/fruta-de-lychee-11963754.jpg",
  },
  {
    id: 27,
    genus: "Genus: Mangifera",
    name: "Mango",
    family: "Family: Anacardiaceae",
    order:"Order: Sapindales",
    description:"carbohydrates: 15, protein: 0.82, fat: 0.38, calories: 60, sugar: 13.7",
    image:"https://thumbs.dreamstime.com/b/frutos-da-manga-no-fundo-branco-39271382.jpg",
  },
  {
    id: 41,
    genus: "Genus: Cucumis",
    name: "Melon",
    family: "Family: Cucurbitaceae",
    order:"Order: Cucurbitaceaes",
    description:"carbohydrates: 8, protein: 0, fat: 0, calories: 34, sugar: 8",
    image:"https://img.freepik.com/vetores-premium/conjunto-de-frutas-frescas-de-melao-meia-fatia-cortadas-inteiras-isoladas-no-fundo-branco-melao-honeydew-frutas-de-verao-para-um-estilo-de-vida-saudavel-fruta-organica-ilustracao-em-vetor-3d-realista-para-qualquer-projeto_545793-1000.jpg?w=2000",
  },
  {
    id: 2,
    genus: "Genus: Citrus",
    name: "Orange",
    family: "Family: Rutaceae",
    order:"Order: Sapindales",
    description:"carbohydrates: 8.3, protein: 1, fat: 0.2, calories: 43, sugar: 8.2",
    image:"https://i.pinimg.com/736x/1e/a2/e8/1ea2e897481ef298c6ba1c14cffce510.jpg",
  }, 
  {
    id: 42,
    genus: "Genus: Carica",
    name: "Papaya",
    family: "Family: Caricaceae",
    order:"Order: Caricacea",
    description:"carbohydrates: 11, protein: 0, fat: 0.4, calories: 43, sugar: 1",
    image:"https://st4.depositphotos.com/10232124/20486/i/450/depositphotos_204867552-stock-photo-whole-half-ripe-papaya-fruit.jpg",
  },
  {
    id: 70,
    genus: "Genus: Passiflora",
    name: "Passionfruit",
    family: "Family: Passifloraceae",
    order:"Order: Malpighiales",
    description:"carbohydrates: 22.4, protein: 2.2, fat: 0.7, calories: 97, sugar: 11.2",
    image:"https://st3.depositphotos.com/1049691/32516/i/450/depositphotos_325163394-stock-photo-fresh-passion-fruit-on-white.jpg",
  },  
  {
    id: 4,
    genus: "Genus: Pyrus",
    name: "Pear",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"carbohydrates: 15, protein: 0.4, fat: 0.1, calories: 57, sugar: 10",
    image:"https://static.vecteezy.com/ti/fotos-gratis/p2/3281465-fruta-pera-verde-isolada-no-fundo-branco-gr%C3%A1tis-foto.jpg",
  },
  {
    id: 52,
    genus: "Genus: Diospyros",
    name: "Persimmon",
    family: "Family: Ebenaceae",
    order:"Order: Rosales",
    description:"carbohydrates: 18, protein: 0, fat: 0, calories: 81, sugar: 18",
    image:"https://thumbs.dreamstime.com/b/frutos-de-persimmons-desagrad%C3%A1veis-kaki-em-fundo-branco-persimmon-frutas-agricultura-antioxidante-asi%C3%A1tico-outono-belo-natal-170813246.jpg",
  },
  {
    id: 10,
    genus: "Genus: Ananas",
    name: "Pineapple",
    family: "Family: Bromeliaceae",
    order:"Order: Poales",
    description:"carbohydrates: 13.12, protein: 0.54, fat: 0.12, calories: 50, sugar: 9.85",
    image:"https://img.freepik.com/fotos-premium/fruta-de-abacaxi-em-um-fundo-branco_35378-1979.jpg",
  },
  {
    id: 71,
    genus: "Genus: Prunus",
    name: "Plum",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"carbohydrates: 11.4, protein: 0.7, fat: 0.28, calories: 46, sugar: 9.92",
    image:"https://st3.depositphotos.com/25607524/33092/i/450/depositphotos_330920332-stock-photo-graphic-resources-isolated-plum-fruit.jpg",
  },
  {
    id: 23,
    genus: "Genus: Rubus",
    name: "Raspberry",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"carbohydrates: 12, protein: 1.2, fat: 0.7, calories: 53, sugar: 4.4",
    image:"https://st3.depositphotos.com/2125603/34618/i/450/depositphotos_346187236-stock-photo-raspberry-fruit-closeup-isolated-white.jpg",
  },
  {
    id: 3,
    genus: "Genus: Fragaria",
    name: "Strawberry",
    family: "Family: Rosaceae",
    order:"Order: Rosales",
    description:"carbohydrates: 5.5, protein: 0.8, fat: 0.4, calories: 29, sugar: 5.4",
    image:"https://thumbs.dreamstime.com/b/morango-com-metade-cortada-isolada-no-fundo-branco-104168374.jpg",
  },
  {
    id: 5,
    genus: "Genus: Solanum",
    name: "Tomato",
    family: "Family: Solanaceae",
    order:"Order: Solanales",
    description:"carbohydrates: 3.9, protein: 0.9, fat: 0.2, calories: 74, sugar: 2.6",
    image:"https://thumbs.dreamstime.com/b/col%C3%ADrio-de-tomate-sobre-fundo-branco-quando-maduro-%C3%A9-vermelho-ou-laranja-tomates-para-cozinhar-e-comer-frutas-frescas-164562805.jpg",
  },
  {
    id: 73,
    genus: "Genus: Spondias",
    name: "Umbu",
    family: "Family: Anacardiaceae",
    order:"Order: 0",
    description:"carbohydrates: 0, protein: 0, fat: 0, calories: 0, sugar: 0",
    image:"https://media.istockphoto.com/photos/umbu-fruit-isolated-on-white-background-picture-id1126023246?k=20&m=1126023246&s=170667a&w=0&h=PCYBXtvXEoKBvi0NnVQYM0twS3bET-QAgVUkiUgB70M=",
  },
  {
    id: 25,
    genus: "Genus: Citrullus",
    name: "Watermelon",
    family: "Family: Cucurbitaceae",
    order:"Order: Cucurbitales",
    description:"carbohydrates: 8, protein: 0.6, fat: 0.2, calories: 30, sugar: 6",
    image:"https://img.freepik.com/fotos-premium/fruta-melancia-em-fundo-branco_255512-1125.jpg?w=2000",
  },
];

export default data;